### ISSUE TITLE
HOL 1, Ex 7, Step 12 - Azure Portal walkthrough

### ISSUE THREAD

**Issue by Senajs** [AzureCAT-GSI/DevCamp#135]
Following screen shot might be the correct one:

Navigation path:
•	DevCamp/HOL/dotnet/01-developer-environment/
•	Developer Environment (.NET)
•	Exercise 7: Azure Portal walkthrough
12. The Windows VM uses DevTest labs to manage the start up and shut down 
![azureportal](https://cloud.githubusercontent.com/assets/15032819/21220611/bfc89f98-c2df-11e6-9ce7-aa849552ac2d.jpg)

**Comment by stevenfollis** [comment]
Unclear as to what the issue is - the screenshots and writeup have been updated to use DTL policies for shutdown and startup. The screenshot's difference is that it is using the search feature to navigate to the DTL, whereas the documentation navigates via a Resource Group. 

@Senajs any more context or is the screenshot just showing an alternative way to navigate to the DTL Policies?

**Comment by Senajs** [comment]
@stevenfollis the documentation Claims "DevTestLabs" but the reality is "Devcamp"...

**Comment by stevenfollis** [comment]
Thanks for the clarification! I see where this could be confusing as:
* "DevTestLabs" = the Azure Resource being used
* "DevCamp" = the name of one instance of the Azure DevTest Labs service

I'm updating the wording and adding a link to the service documentation to hopefully make it more clear

**Comment by Senajs** [comment]
great- will Keep you updated.
