### ISSUE TITLE
HOL3 - Sending email broken

### ISSUE THREAD

**Issue by stevenfollis** [AzureCAT-GSI/DevCamp#44]
New incident creates without an error, but email never appears

**Comment by stevenfollis** [comment]
Permission missing?

**Comment by amang2205** [comment]
The Graph API 1.0 is returning a 403 HTTP status code, and the message of the returned error object (serialized as JSON) is 'Access is denied. Check credentials and try again.'

**Comment by amang2205** [comment]
OK, here's a solution to the problem. Turns out that it was permission-related.
Adding 'Mail Send' as a delegated permission or 'Mail.Send (admin only)' as an application permission should solve the problem. Specifically, adding Mail.Send as a scope in web.config isn't enough, as for two reasons (I believe):
1) Graph API 1.0 doesn't support (AFAIK, I might be wrong here) dynamic scope request.
2) Having the token request operation done programmatically, users cannot give consent for the extra scope.
Especially because of the 2nd case, I was required to revoke the application permission from my O365 account and grant the application permissions again. This time, the application also requested Mail sending permissions and everything works.
![capture](https://cloud.githubusercontent.com/assets/5773281/20466540/7a9cee92-af75-11e6-984b-7e2282d126d1.PNG)

**Comment by rsponholtz** [comment]
We need to know the process for adding these permission to existing users.

**Comment by stevenfollis** [comment]
@rsponholtz Which existing users? Once they change permissions in the apps portal it should re-auth?

**Comment by ivegamsft** [comment]
This is fixed. Reopen or log again for changes in permissions.
